[platformio]
default_envs = esp32dev
src_dir = src

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  links2004/WebSockets@^2.7.2
  bblanchon/ArduinoJson@^6.21.5
build_flags =
  -DCORE_DEBUG_LEVEL=3
